name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            jhell/car-stats:latest
            jhell/car-stats:${{ github.run_number }}.${{ github.run_attempt }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Update api deployment image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.29.1
          command: set image deployment/car-stats-deployment car-stats=jhell/car-stats:${{ github.run_number }}.${{ github.run_attempt }}
